#!/usr/local/bin bash

brew cask install phoenix
brew install autojump watch tree the_silver_searcher tig fzy

git clone git://github.com/ndbroadbent/scm_breeze.git ~/.scm_breeze
~/.scm_breeze/install.sh
source ~/.zshrc'

cat "zsh_aliases" >> "~/.zshrc"
