#!/usr/local/bin bash

brew cask install phoenix
brew install entr autojump watch tree fpp the_silver_searcher

git clone git://github.com/ndbroadbent/scm_breeze.git ~/.scm_breeze
~/.scm_breeze/install.sh
source ~/.zshrc'

gem install lunchy

cat "zsh_aliases" >> "~/.zshrc"
