#!/usr/local/bin bash

brew install entr autojump watch tree fpp

git clone git://github.com/ndbroadbent/scm_breeze.git ~/.scm_breeze
~/.scm_breeze/install.sh
source ~/.bashrc

gem install lunchy

cat "zsh_aliases" >> "~/.zshrc"
